### ISSUE TITLE
Could this be used as a possible public account validation?

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Robot-Launcher#1]
or could that be a possible future feature?

**Comment by Alexander01998** [comment]
What could be used as what?

**Comment by pokeball99** [comment]
well it just if u have no alts,just get a scraper for pastebin and load it up in there and use the proxys to check it on here,any that work well get logged in,any that don't,gets deleted

**Comment by Alexander01998** [comment]
> well it just if u have no alts,just get a scraper for pastebin and load it up in there and use the proxys to check it on here,any that work well get logged in,any that don't,gets deleted

No, that's not the purpose of this program.

I have made an alt checker long ago. It's discontinued, but you can still download it on [the old Wurst Client website](https://old.wurst-client.tk/download/altchecker/releases).
